### PR TITLE
Unfork teensyduino and run buildgen at build time

### PR DESCRIPTION
**Pull request by SimonSapin**
@jamesmunns I’m traveling and don’t have hardware with me to try this. Could you try building something with this and run it on real hardware to make sure I didn’t screw up startup code or something?

### CODE REVIEW

**Comment by SimonSapin** [comment]
This probably could use some instructions in `README.md` with at least a link to https://github.com/servo/rust-bindgen#requirements

**Comment by jamesmunns** [comment]
@SimonSapin +1 I can test with the teensy 3.2 hardware tonight, and after I'm happy to sign off, I can ping some of the other people who were willing to test a 3.0/3.5/3.6 to see if they are still interested.

**Comment by SimonSapin** [comment]
> people who were willing to test a 3.0/3.5/3.6

Actually supporting other hardware doesn’t work yet! And I don’t know want to make promises about when I’d get to making it happen :)

**Comment by jamesmunns** [comment]
```
--- Miniterm on /dev/ttyACM0  115200,8,N,1 ---
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
Hello Teensy Rusty World!
```

@SimonSapin Passes my smoke test. Okay to merge and re-publish crates.

**Pull request merged**
